### ISSUE TITLE
how to relay tracks to arbitrary number of sfu nodes?

### ISSUE THREAD

**Issue by vertextao** [pion/ion-sfu#525]
According to the relay feature committed up to now in the master branch[fe3108], I comprehend that the design is every publisher can relay its tracks to only ONE destination. @OrlandoCo Is my comprehension right?

But IMO, as a distributed conference system, users could access the system from anywhere, therefore, we could deploy numbers of SFU nodes in different location for lower latency for end users. Suppose users join the same room though 3 different SFU nodes, every publisher's tracks should be relayed to 2 other SFU nodes, in other words, SFUs belong to a same room works as MESH mode.

So, is the relay feature WIP designed to satisfy the situation? 

I propose to have more discussion on this feature.

**Comment by cloudwebrtc** [comment]
@vertextao The implementation of this issue is included in the ion function. 
My idea is that a certain session must first be globally located in the distributed system, such as `dc1/sfu01/test_room01`, so this session is in the sfu01 node, and there are additional ones in the cluster For a sfu02, sfu03 node,
You need to use the copy or bridge command (sfu relay) `dc1/sfu01/test_room01` => `dc2/sfu02/test_room01`, so when you connect to a different sfu server (no matter sfu01 or sfu02), you will all enter the `test_room01` room and see Everyone.

**Comment by OrlandoCo** [comment]
@vertextao Relay is still work in progress, but in the future you will call `peer.Relay()` this will return a single message that you will need to relay to whatever service you want to get the feeds, of course you will be able to call relay anytime

If you want to discuss more feel free to join ion slack channel.

**Comment by vertextao** [comment]
@cloudwebrtc Your idea looks like a good option. But as @OrlandoCo 's work is in progress, I'm not sure about what his final version would look like. For convenience, let's have more discussion in the slack channel.
