### ISSUE TITLE
(feat) replace logger

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#534]
## Let's discuss about the logger
This is the logger screenshot in sfu:
![image](https://user-images.githubusercontent.com/12995347/119220433-2ab6c980-bb1d-11eb-9636-61c4a322d40a.png)

## This is the logger's feature what i know:
* print with key-value pairs, this can reduce some words, like:
Logger.Info("before RemoveDownTrack", "streamid", id)
It will automate add `=` and a `v=0`
```
[2021-05-22 16:18:51.817] [INFO] [subscriber.go:155] => before RemoveDownTrack streamid=5e6b37e2-4de9-416c-ad40-b981e78fb07a v=0
```
* automate print a version: `v=0|1|..` i think it's useless and confusing
* automate make the Key a green color, like `v=0` and `streamid=`
* **I found logger didn't print some pointer var**

This is my code:
```
func (s *Subscriber) RemoveDownTrack(streamID string, downTrack *DownTrack) {
    s.Lock()
    defer s.Unlock()
    for id, dtracks := range s.tracks {
        Logger.Info("before RemoveDownTrack", "streamid", id)
        for _, dtrack := range dtracks {
            Logger.Info("before RemoveDownTrack", "dtrack", dtrack)
        }
    }
```
and the log, `dtrack={}`, more info in dtrack can't be printed :
```
[2021-05-22 16:18:51.817] [INFO] [subscriber.go:155] => before RemoveDownTrack streamid=5e6b37e2-4de9-416c-ad40-b981e78fb07a v=0
[2021-05-22 16:18:51.817] [INFO] [subscriber.go:157] => before RemoveDownTrack dtrack={} v=0
[2021-05-22 16:18:51.817] [INFO] [subscriber.go:157] => before RemoveDownTrack dtrack={} v=0
[2021-05-22 16:18:51.817] [INFO] [subscriber.go:175] => before RemoveDownTrack streamid=5e6b37e2-4de9-416c-ad40-b981e78fb07a v=0
```

## About ion-log
This is ion-log screenshot
![image](https://user-images.githubusercontent.com/12995347/119220510-723d5580-bb1d-11eb-8833-951ceaf37cd7.png)
I think it's better:
* It's colorful
* It's used in other ion module, worked fine, base on logrus
* It's very flexible, you can control your level, your pkg prefix and var printing format， for example：
* can control different levels on different prefixs 
```
var (
      logger = log.NewLoggerWithFields(log.DebugLevel, "your_pkg_prefix", nil)
)
    logger.Debug("Hello ION!", logger)
    logger.Debugf("Hello ION! logger=%+v", logger)
```
This is very useful, different  pkg/service can use different prefix, you can filter log by `grep|yourprefix`

**Comment by adwpc** [comment]
@mikhno-s @bshi @OrlandoCo @billylindeman @cloudwebrtc

**Comment by tarrencev** [comment]
the logger is configurable, so you can implement the interface with `ion-log` and pass it to the sfu. `ion-sfu` itself should not prescribe a logger. does `ion` extend `ion-sfu` or are you using the built in signaling?

**Comment by adwpc** [comment]
> the logger is configurable, so you can implement the interface with `ion-log` and pass it to the sfu. `ion-sfu` itself should not prescribe a logger. does `ion` extend `ion-sfu` or are you using a prebuilt version?

two scenes：
1 import ion-sfu as package in ion
2 debug ion-sfu but the Logger cant print member of struct，see above

**Comment by bshi** [comment]
> This is the logger's feature what i know:

These are not the logger's features.  These are simply the default settings for the default https://github.com/go-logr/logr implementation (which uses zerolog).  If they are not consistent, you can (to an extent that we can maintain compatibility with https://github.com/go-logr/logr) replace the implementation with something more aligned with your requirements (set Logger in your program's initialization code https://github.com/pion/ion-sfu/blob/master/pkg/sfu/sfu.go#L22)

As @tarrencev has mentioned, library code should not prescribe the behavior of logging if possible.  If you feel the defaults should be changed, that's probably a separate discussion.  Honestly though, logging requirements between even developer and production environments inside a single organization will be wildly different let alone between different organizations (which is why we've opted for flexibility/pluggability) so I suspect fiddling with defaults isn't very good ROI.

> 2 debug ion-sfu but the Logger cant print member of struct

https://github.com/go-logr/logr#but-i-really-want-to-use-a-format-string discusses the trade-offs at play.

**Comment by adwpc** [comment]
![image](https://user-images.githubusercontent.com/12995347/131245474-0274c98c-c712-456d-8018-838ad436d107.png)
@bshi seem the `logr.go:208` is not right position, how to fix?

**Comment by bshi** [comment]
I _believe_ you can tweak the call depth (probably needs to be reduced by 1?) https://pkg.go.dev/github.com/go-logr/logr#Logger.WithCallDepth

Where's the logr.Logger instance that's emitting this?

**Comment by adwpc** [comment]
> 我_相信_您可以调整调用深度（可能需要减少 1？）https://pkg.go.dev/github.com/go-logr/logr#Logger.WithCallDepth
> 
> 发出这个的 logr.Logger 实例在哪里？

![image](https://user-images.githubusercontent.com/12995347/132120858-123052cb-6675-44f0-888a-0c2457325282.png)
	ion_sfu_log.SetGlobalOptions(ion_sfu_log.GlobalConfig{V: 1})
	sfu.Logger = logrLogger.WithName("sfu").WithCallDepth(1)
	
looks bad..
