### ISSUE TITLE
fix examples

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#56]
`pub-from-browser`, `pub-from-disk`, and `sub-to-browser` gRPC examples need to be updated to the new interface

**Comment by vicramon** [comment]
Hey there, I'm trying to get ion-sfu working. Was just starting to test it out, and I was wondering if `pub-sub-in-browser` also needs updating? Here's what's happening for me right now:

```
$ ./main -c config.toml -p 7000
```

Returns:
```
flag provided but not defined: -p
Usage of ./main:
  -a string
    	listen addr (default "0.0.0.0:7000")
  -c string
    	config file (default "config.toml")
  -cert string
    	cert file
  -h	help info
  -key string
    	key file
```

Alright, the default port is 7000 anyway, so I ran:

```
./main -c config.toml

# that works:
#=> config config.toml load ok!
#=> [2020-08-01 20:34:34.099] [INFO] [203][proc.go][main] => Listening at http://[0.0.0.0:7000]
```

1. The websocket connects successfully 
2. Clicking publish gives me the message "Publishing local stream",
3. Hitting subscribe returns "Subscribing to remote stream: undefined". 

The system also never hits this log `Publishing local published with mid: ${mid}`

I also tried with docker, but I'm not sure of the correct command to get it working. I ran `docker run -p 50051:50051 -p 5000-5020:5000-5020/udp pion/ion-sfu:latest`, but the websocket was not able connect. Probably a port problem I'm guessing? 

Let me know if it's working for you and I can keep digging, I'm just a bit new to Go & Docker.

**Comment by tarrencev** [comment]
@vicramon i just updated some docs. looks like the fiddle was also out of date and adam fixed that. please let me know if you run into any other issues (feel free to open an issue)

**Comment by vicramon** [comment]
Great, thanks. I'm confirming that `pub-sub-in-browser` example in the browser is now working for me. I would have saved myself a few hours if I had just started playing with this project a few hours later haha. 

Two quick other things while I'm here:
- It looks like the slack is invite-only – not sure if that's intentional, but because there's a slack badge on the repo, I thought it might have been a mistake. 
- Do you know if there are any docs around deployment? I will probably try to get this thing up on Heroku today.

**Comment by tarrencev** [comment]
the slack channel is on the public gophers slack instance.

for deployment, there isn't docs specifically for `ion-sfu` right now
